"use client";

import Link from "next/link";
import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { useState } from "react";
import { useAuth } from "@/features/auth/auth-provider";
import { useLanguage } from "@/features/i18n/language-context";
import { saveFeedback, saveInquiry } from "@/services/persistence-service";
import { FeedbackStatus, InquiryStatus } from "@/types/domain";

const inquirySchema = z.object({ name: z.string().trim().min(2, "Masukkan nama Anda."), contact: z.string().trim().min(5, "Masukkan kontak yang dapat dihubungi.").refine((value) => /@/.test(value) || /^[+\d][\d\s().-]{7,}$/.test(value), "Masukkan email atau nomor telepon yang valid."), service: z.string().min(1, "Pilih layanan."), purpose: z.string().trim().min(10, "Jelaskan tujuan atau keluhan singkat (min. 10 karakter).").max(500, "Maksimal 500 karakter."), date: z.string().min(1, "Pilih preferensi tanggal.").refine((value) => value >= new Date().toISOString().slice(0, 10), "Pilih tanggal hari ini atau setelahnya."), travel: z.boolean(), privacy: z.literal(true, { error: "Persetujuan privasi diperlukan." }) });
type InquiryValues = z.infer<typeof inquirySchema>;
const recordId = (prefix: string) => `${prefix}-${Date.now()}`;

export function InquiryForm({ organizationId, services, returnTo }: { organizationId: string; services: string[]; returnTo: string }) {
  const { isEnglish } = useLanguage();
  const { status, user } = useAuth();
  const [sent, setSent] = useState(false);
  const [submitError, setSubmitError] = useState("");
  const { register, handleSubmit, formState: { errors } } = useForm<InquiryValues>({ resolver: zodResolver(inquirySchema), defaultValues: { travel: false } });
  const copy = isEnglish ? { authTitle: "Submit an inquiry with an account", authCopy: "Create an account or sign in first so inquiries, schedules, and partner updates stay securely in your dashboard.", create: "Create an account for inquiry", signIn: "I already have an account", sent: "Inquiry sent.", sentCopy: "The partner will follow up using the contact details you provided.", title: "Service inquiry", intro: "Briefly describe your need. Do not include lab results, medical records, identity documents, or emergency information.", name: "Name", contact: "Phone number or email", service: "Service of interest", choose: "Choose a service", purpose: "Brief purpose or concern", placeholder: "Example: I would like an initial consultation and information about the available examination process.", date: "Preferred date", travel: "I need travel support", privacy: "I consent to processing my contact details and inquiry purpose for service follow-up.", submit: "Send inquiry" } : { authTitle: "Ajukan inquiry dengan akun", authCopy: "Buat akun atau masuk terlebih dahulu agar inquiry, jadwal, dan pembaruan dari mitra tersimpan aman dalam dashboard Anda.", create: "Buat akun untuk inquiry", signIn: "Saya sudah punya akun", sent: "Inquiry terkirim.", sentCopy: "Mitra akan menindaklanjuti melalui kontak yang Anda berikan.", title: "Inquiry layanan", intro: "Tuliskan kebutuhan secara singkat. Jangan masukkan hasil lab, rekam medis, dokumen identitas, atau informasi gawat darurat.", name: "Nama", contact: "Nomor kontak atau email", service: "Layanan yang diminati", choose: "Pilih layanan", purpose: "Tujuan konsultasi / keluhan singkat", placeholder: "Contoh: ingin konsultasi awal dan mengetahui alur pemeriksaan yang tersedia.", date: "Preferensi tanggal", travel: "Saya membutuhkan dukungan perjalanan", privacy: "Saya menyetujui pemrosesan data kontak dan tujuan inquiry untuk tindak lanjut layanan.", submit: "Kirim inquiry" };
  const submit = async (value: InquiryValues) => { setSubmitError(""); try { await saveInquiry({ id: recordId("INQ"), organizationId, name: value.name.trim(), contact: value.contact.trim(), service: value.service, purpose: value.purpose.trim(), date: value.date, needsTravel: value.travel, status: InquiryStatus.New, createdAt: "Baru saja" }, user?.$id); setSent(true); } catch { setSubmitError(isEnglish ? "We could not save this inquiry. Please try again." : "Inquiry belum dapat disimpan. Silakan coba lagi."); } };
  if (status !== "authenticated") { const next = encodeURIComponent(returnTo); return <section className="card inquiry-auth-card" style={{ padding: 22, display: "grid", gap: 13 }}><h2 style={{ margin: 0, color: "var(--navy)", fontSize: 20 }}>{copy.authTitle}</h2><p className="hint" style={{ margin: 0, lineHeight: 1.55 }}>{copy.authCopy}</p><Link className="btn btn-primary" href={`/register?next=${next}`}>{copy.create}</Link><Link className="btn btn-outline" href={`/login?next=${next}`}>{copy.signIn}</Link></section>; }
  if (sent) return <div className="card" style={{ padding: 22, background: "#edfbf7" }}><b>{copy.sent}</b><p style={{ marginBottom: 0 }}>{copy.sentCopy}</p></div>;
  return <form className="card" style={{ padding: 22, display: "grid", gap: 14 }} onSubmit={handleSubmit(submit)}><h2 style={{ margin: 0, color: "var(--navy)", fontSize: 20 }}>{copy.title}</h2><p className="hint" style={{ margin: 0 }}>{copy.intro}</p><label className="field">{copy.name}<input className="input" {...register("name")} />{errors.name && <Error message={errors.name.message} />}</label><label className="field">{copy.contact}<input className="input" {...register("contact")} />{errors.contact && <Error message={errors.contact.message} />}</label><label className="field">{copy.service}<select className="input" {...register("service")}><option value="">{copy.choose}</option>{services.map((service) => <option key={service}>{service}</option>)}</select>{errors.service && <Error message={errors.service.message} />}</label><label className="field">{copy.purpose}<textarea className="input" rows={4} maxLength={500} placeholder={copy.placeholder} {...register("purpose")} />{errors.purpose && <Error message={errors.purpose.message} />}</label><label className="field">{copy.date}<input type="date" min={new Date().toISOString().slice(0, 10)} className="input" {...register("date")} />{errors.date && <Error message={errors.date.message} />}</label><label style={{ fontSize: 14 }}><input type="checkbox" {...register("travel")} /> {copy.travel}</label><label style={{ fontSize: 13 }}><input type="checkbox" {...register("privacy")} /> {copy.privacy} <Link href="/privacy" style={{ color: "var(--teal)", textDecoration: "underline" }}>{isEnglish ? "Read privacy notice" : "Baca pemberitahuan privasi"}</Link></label>{errors.privacy && <Error message={errors.privacy.message} />}{submitError && <Error message={submitError} />}<button className="btn btn-primary" type="submit">{copy.submit}</button></form>;
}

function Error({ message }: { message?: string }) { return <span className="hint" style={{ color: "#b3261e" }}>{message}</span>; }

const feedbackSchema = z.object({ category: z.string().min(1, "Pilih kategori."), message: z.string().min(12, "Ceritakan sedikit lebih lengkap (min. 12 karakter)."), contact: z.string().optional() });
type FeedbackValues = z.infer<typeof feedbackSchema>;
export function FeedbackForm() {
  const { isEnglish } = useLanguage();
  const [sent, setSent] = useState(false);
  const [submitError, setSubmitError] = useState("");
  const { user } = useAuth();
  const { register, handleSubmit, formState: { errors } } = useForm<FeedbackValues>({ resolver: zodResolver(feedbackSchema) });
  const copy = isEnglish ? { thanks: "Thank you for your feedback.", received: "The report has been received by the committee for review.", category: "Category", choose: "Choose a category", message: "Message", contact: "Contact (optional)", submit: "Send feedback", options: ["Incorrect information", "Difficulty contacting a partner", "Suspected service standard violation", "Accessibility issue", "Other"] } : { thanks: "Terima kasih atas masukan Anda.", received: "Laporan diterima panitia untuk ditinjau.", category: "Kategori", choose: "Pilih kategori", message: "Pesan", contact: "Kontak (opsional)", submit: "Kirim masukan", options: ["Informasi tidak sesuai", "Kesulitan menghubungi mitra", "Dugaan pelanggaran standar layanan", "Kendala aksesibilitas", "Lainnya"] };
  const submit = async (value: FeedbackValues) => { setSubmitError(""); try { await saveFeedback({ id: recordId("FB"), category: value.category, message: value.message.trim(), contact: value.contact?.trim(), status: FeedbackStatus.New, createdAt: "Baru saja" }, user?.$id); setSent(true); } catch { setSubmitError(isEnglish ? "We could not send this feedback. Please try again." : "Masukan belum dapat dikirim. Silakan coba lagi."); } };
  if (sent) return <div className="card" style={{ padding: 24, background: "#edfbf7" }}><b>{copy.thanks}</b><p style={{ marginBottom: 0 }}>{copy.received}</p></div>;
  return <form className="card" style={{ padding: 24, display: "grid", gap: 15 }} onSubmit={handleSubmit(submit)}><label className="field">{copy.category}<select className="input" {...register("category")}><option value="">{copy.choose}</option>{copy.options.map((category) => <option key={category}>{category}</option>)}</select>{errors.category && <Error message={errors.category.message} />}</label><label className="field">{copy.message}<textarea rows={5} className="input" {...register("message")} />{errors.message && <Error message={errors.message.message} />}</label><label className="field">{copy.contact}<input className="input" {...register("contact")} /></label>{submitError && <Error message={submitError} />}<button className="btn btn-primary" type="submit">{copy.submit}</button></form>;
}
