"use client";

import Link from "next/link";
import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { useState } from "react";
import { useAuth } from "@/features/auth/auth-provider";
import { dataService } from "@/services/data-service";
import { FeedbackStatus, InquiryStatus } from "@/types/domain";

const inquirySchema = z.object({ name: z.string().min(2, "Masukkan nama Anda."), contact: z.string().min(5, "Masukkan kontak yang dapat dihubungi."), service: z.string().min(1, "Pilih layanan."), purpose: z.string().min(10, "Jelaskan tujuan atau keluhan singkat (min. 10 karakter).").max(500, "Maksimal 500 karakter."), date: z.string().min(1, "Pilih preferensi tanggal."), travel: z.boolean(), privacy: z.literal(true, { error: "Persetujuan privasi diperlukan." }) });
type InquiryValues = z.infer<typeof inquirySchema>;

export function InquiryForm({ organizationId, services, returnTo }: { organizationId: string; services: string[]; returnTo: string }) {
  const { status } = useAuth(); const [sent, setSent] = useState(false);
  const { register, handleSubmit, formState: { errors } } = useForm<InquiryValues>({ resolver: zodResolver(inquirySchema), defaultValues: { travel: false } });
  const submit = (value: InquiryValues) => { dataService.addInquiry({ id: "INQ-DEMO-NEW", organizationId, name: value.name, contact: value.contact, service: value.service, purpose: value.purpose, date: value.date, needsTravel: value.travel, status: InquiryStatus.New, createdAt: "Baru saja" }); setSent(true); };
  if (status !== "authenticated") { const next = encodeURIComponent(returnTo); return <section className="card" style={{ padding: 22, display: "grid", gap: 13 }}><h2 style={{ margin: 0, color: "var(--navy)", fontSize: 20 }}>Ajukan inquiry dengan akun</h2><p className="hint" style={{ margin: 0, lineHeight: 1.55 }}>Buat akun atau masuk terlebih dahulu agar inquiry, jadwal, dan pembaruan dari mitra tersimpan aman dalam dashboard Anda.</p><Link className="btn btn-primary" href={`/register?next=${next}`}>Buat akun untuk inquiry</Link><Link className="btn btn-outline" href={`/login?next=${next}`}>Saya sudah punya akun</Link></section>; }
  if (sent) return <div className="card" style={{ padding: 22, background: "#edfbf7" }}><b>Inquiry terkirim.</b><p style={{ marginBottom: 0 }}>Mitra akan menindaklanjuti melalui kontak yang Anda berikan.</p></div>;
  return <form className="card" style={{ padding: 22, display: "grid", gap: 14 }} onSubmit={handleSubmit(submit)}><h2 style={{ margin: 0, color: "var(--navy)", fontSize: 20 }}>Inquiry layanan</h2><p className="hint" style={{ margin: 0 }}>Tuliskan kebutuhan secara singkat. Jangan masukkan hasil lab, rekam medis, dokumen identitas, atau informasi gawat darurat.</p><label className="field">Nama<input className="input" {...register("name")} />{errors.name && <Error message={errors.name.message} />}</label><label className="field">Nomor kontak atau email<input className="input" {...register("contact")} />{errors.contact && <Error message={errors.contact.message} />}</label><label className="field">Layanan yang diminati<select className="input" {...register("service")}><option value="">Pilih layanan</option>{services.map((service) => <option key={service}>{service}</option>)}</select>{errors.service && <Error message={errors.service.message} />}</label><label className="field">Tujuan konsultasi / keluhan singkat<textarea className="input" rows={4} maxLength={500} placeholder="Contoh: ingin konsultasi awal dan mengetahui alur pemeriksaan yang tersedia." {...register("purpose")} />{errors.purpose && <Error message={errors.purpose.message} />}</label><label className="field">Preferensi tanggal<input type="date" className="input" {...register("date")} />{errors.date && <Error message={errors.date.message} />}</label><label style={{ fontSize: 14 }}><input type="checkbox" {...register("travel")} /> Saya membutuhkan dukungan perjalanan</label><label style={{ fontSize: 13 }}><input type="checkbox" {...register("privacy")} /> Saya menyetujui pemrosesan data kontak dan tujuan inquiry untuk tindak lanjut layanan.</label>{errors.privacy && <Error message={errors.privacy.message} />}<button className="btn btn-primary" type="submit">Kirim inquiry</button></form>;
}
function Error({ message }: { message?: string }) { return <span className="hint" style={{ color: "#b3261e" }}>{message}</span>; }

const feedbackSchema = z.object({ category: z.string().min(1, "Pilih kategori."), message: z.string().min(12, "Ceritakan sedikit lebih lengkap (min. 12 karakter)."), contact: z.string().optional() });
type FeedbackValues = z.infer<typeof feedbackSchema>;
export function FeedbackForm() { const [sent, setSent] = useState(false); const { register, handleSubmit, formState: { errors } } = useForm<FeedbackValues>({ resolver: zodResolver(feedbackSchema) }); const submit = (value: FeedbackValues) => { dataService.addFeedback({ id: "FB-DEMO-NEW", category: value.category, message: value.message, contact: value.contact, status: FeedbackStatus.New, createdAt: "Baru saja" }); setSent(true); }; if (sent) return <div className="card" style={{ padding: 24, background: "#edfbf7" }}><b>Terima kasih atas masukan Anda.</b><p style={{ marginBottom: 0 }}>Laporan diterima panitia untuk ditinjau.</p></div>; return <form className="card" style={{ padding: 24, display: "grid", gap: 15 }} onSubmit={handleSubmit(submit)}><label className="field">Kategori<select className="input" {...register("category")}><option value="">Pilih kategori</option>{["Informasi tidak sesuai", "Kesulitan menghubungi mitra", "Dugaan pelanggaran standar layanan", "Kendala aksesibilitas", "Lainnya"].map((category) => <option key={category}>{category}</option>)}</select>{errors.category && <Error message={errors.category.message} />}</label><label className="field">Pesan<textarea rows={5} className="input" {...register("message")} />{errors.message && <Error message={errors.message.message} />}</label><label className="field">Kontak (opsional)<input className="input" {...register("contact")} /></label><button className="btn btn-primary" type="submit">Kirim feedback</button></form>; }
