"use client";

import { useMemo, useState } from "react";
import { Search, SlidersHorizontal } from "lucide-react";
import { PublicShell } from "@/components/layouts/public-shell";
import { PartnerCard } from "@/features/catalog/components/partner-card";
import { useLanguage } from "@/features/i18n/language-context";
import { dataService } from "@/services/data-service";
import { PartnerType } from "@/types/domain";

const typeLabels = { Semua: "All", "Rumah Sakit": "Hospital", "Klinik": "Clinic", Hotel: "Hotel", "Travel Agent": "Travel agent", Penerjemah: "Interpreter" } as const;

export default function Explore() {
  const { isEnglish } = useLanguage();
  const [q, setQ] = useState("");
  const [type, setType] = useState("Semua");
  const [area, setArea] = useState("Semua");
  const [accessible, setAccessible] = useState(false);
  const list = useMemo(() => dataService.listPublic().filter((x) => (type === "Semua" || x.type === type) && (area === "Semua" || x.area === area) && (!accessible || x.accessibility.length > 0) && (`${x.name} ${x.services.join(" ")}`.toLowerCase().includes(q.toLowerCase()))), [q, type, area, accessible]);
  const labels = isEnglish ? { eyebrow: "PUBLIC DIRECTORY", title: "Find the right service for your needs.", intro: "Only verified partners are shown. Results are not ranked by payment or commission.", search: "Search services or partners", searchPlaceholder: "Name or service", type: "Partner type", area: "Area", all: "All", accessible: "Accessible", found: "partners found", language: "Languages: Indonesian · English", empty: "No matching results.", emptyCopy: "Try removing one or more filters.", noCharge: "Not ranked by payment or commission." } : { eyebrow: "KATALOG PUBLIK", title: "Temukan layanan yang sesuai kebutuhan Anda.", intro: "Hanya mitra terverifikasi yang ditampilkan. Urutan tidak dipengaruhi pembayaran atau komisi.", search: "Cari layanan atau mitra", searchPlaceholder: "Nama atau layanan", type: "Jenis mitra", area: "Wilayah", all: "Semua", accessible: "Aksesibel", found: "mitra ditemukan", language: "Bahasa: Indonesia · Inggris", empty: "Belum ada hasil yang cocok.", emptyCopy: "Coba hapus satu atau beberapa filter.", noCharge: "Urutan tidak dipengaruhi pembayaran atau komisi." };
  const displayType = (value: string) => isEnglish ? typeLabels[value as keyof typeof typeLabels] ?? value : value;
  return <PublicShell><main className="container" style={{ padding: "50px 0" }}><p style={{ color: "var(--teal)", fontWeight: 800 }}>{labels.eyebrow}</p><h1 className="section-title">{labels.title}</h1><p style={{ maxWidth: 700, color: "#557080", lineHeight: 1.5 }}>{labels.intro}</p><div className="card" style={{ padding: 17, margin: "26px 0", display: "grid", gridTemplateColumns: "2fr repeat(2,1fr) auto", gap: 10 }}><label className="field"><span className="hide-mobile">{labels.search}</span><div style={{ position: "relative" }}><Search size={17} style={{ position: "absolute", left: 10, top: 11, color: "#5c7585" }} /><input className="input" style={{ paddingLeft: 33 }} placeholder={labels.searchPlaceholder} value={q} onChange={(e) => setQ(e.target.value)} /></div></label><label className="field"><span className="hide-mobile">{labels.type}</span><select className="input" value={type} onChange={(e) => setType(e.target.value)}><option value="Semua">{labels.all}</option>{Object.values(PartnerType).map((value) => <option key={value} value={value}>{displayType(value)}</option>)}</select></label><label className="field"><span className="hide-mobile">{labels.area}</span><select className="input" value={area} onChange={(e) => setArea(e.target.value)}><option value="Semua">{labels.all}</option>{["Jakarta Pusat", "Jakarta Selatan", "Jakarta Barat", "Jakarta Timur"].map((value) => <option key={value}>{value}</option>)}</select></label><label className="field" style={{ justifyContent: "end", fontWeight: 500 }}><span className="hide-mobile">&nbsp;</span><span style={{ whiteSpace: "nowrap" }}><input type="checkbox" checked={accessible} onChange={(e) => setAccessible(e.target.checked)} /> {labels.accessible}</span></label></div><div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 16 }}><b>{list.length} {labels.found}</b><span className="hint"><SlidersHorizontal size={14} style={{ verticalAlign: "middle" }} /> {labels.language}</span></div>{list.length ? <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(250px,1fr))", gap: 16 }}>{list.map((x) => <PartnerCard key={x.id} partner={x} />)}</div> : <div className="card" style={{ padding: 34, textAlign: "center" }}><b>{labels.empty}</b><p className="hint">{labels.emptyCopy}</p></div>}</main></PublicShell>;
}
