"use client";

import Link from "next/link";
import { ArrowRight, BadgeCheck, BedDouble, ClipboardCheck, FileText, HelpCircle, MapPinned, MessageCircleQuestion, ShieldCheck, Stethoscope, TrainFront, UsersRound } from "lucide-react";
import { useLanguage } from "@/features/i18n/language-context";

const journeySteps = [
  { number: "01", icon: Stethoscope, title: "Pahami kebutuhan", copy: "Mulai dari layanan yang Anda cari, tanpa memasukkan rekam medis atau informasi darurat.", href: "/explore", cta: "Jelajahi fasyankes" },
  { number: "02", icon: ClipboardCheck, title: "Bandingkan pilihan", copy: "Lihat harga ilustrasi, cakupan, durasi, akses, dan ketentuan dari paket yang relevan.", href: "/compare", cta: "Buka perbandingan" },
  { number: "03", icon: MessageCircleQuestion, title: "Kirim inquiry", copy: "Buat akun agar inquiry, jadwal, dan pembaruan dari mitra tersimpan di dashboard Anda.", href: "/register", cta: "Buat akun" },
  { number: "04", icon: MapPinned, title: "Atur perjalanan", copy: "Tambahkan hotel, travel agent, penerjemah, dan informasi transportasi sesuai kebutuhan.", href: "/support", cta: "Lihat dukungan" },
];

const guideTopics = [
  { icon: BadgeCheck, title: "Memilih fasyankes", copy: "Hal yang perlu dicek pada profil mitra, dokter, layanan, dan status verifikasi.", href: "/explore" },
  { icon: FileText, title: "Membaca paket & harga", copy: "Pahami perbedaan harga mulai, cakupan, pengecualian, dan biaya tambahan.", href: "/compare" },
  { icon: BedDouble, title: "Hotel & kebutuhan menginap", copy: "Bandingkan kamar, fasilitas aksesibel, tarif malam, dan kebijakan booking.", href: "/support" },
  { icon: UsersRound, title: "Penerjemah & pendamping", copy: "Pilih dukungan bahasa dan perjalanan non-medis yang sesuai agenda Anda.", href: "/support" },
  { icon: TrainFront, title: "Tiba di Jakarta", copy: "Gunakan informasi transportasi umum dan akses drop-off di halaman fasyankes.", href: "/explore" },
  { icon: ShieldCheck, title: "Privasi & keselamatan", copy: "Gunakan inquiry untuk koordinasi non-klinis; bukan untuk diagnosis atau keadaan darurat.", href: "/feedback" },
];

const beforeInquiry = ["Nama dan kontak yang dapat dihubungi", "Layanan atau paket yang diminati", "Tujuan kunjungan secara singkat dan non-klinis", "Preferensi tanggal dan kebutuhan perjalanan", "Persetujuan pemrosesan data kontak untuk tindak lanjut"];
const beforeInquiryEn = ["Name and reachable contact details", "Preferred service or package", "A brief, non-clinical visit purpose", "Preferred date and travel needs", "Consent to process contact details for follow-up"];

export function GuidePage() {
  const { isEnglish } = useLanguage();
  const steps = isEnglish ? [
    { number: "01", icon: Stethoscope, title: "Understand your need", copy: "Start with the service you are looking for—without entering medical records or emergency information.", href: "/explore", cta: "Explore facilities" },
    { number: "02", icon: ClipboardCheck, title: "Compare options", copy: "Review illustrative prices, inclusions, duration, access, and terms for relevant packages.", href: "/compare", cta: "Open comparison" },
    { number: "03", icon: MessageCircleQuestion, title: "Send an inquiry", copy: "Create an account so inquiries, schedules, and partner updates stay in your dashboard.", href: "/register", cta: "Create an account" },
    { number: "04", icon: MapPinned, title: "Plan the journey", copy: "Add hotels, travel agents, interpreters, and transport information when needed.", href: "/support", cta: "View support" },
  ] : journeySteps;
  const topics = isEnglish ? [
    { icon: BadgeCheck, title: "Choosing a facility", copy: "What to check on a partner profile, care team, services, and verification status.", href: "/explore" },
    { icon: FileText, title: "Reading packages & prices", copy: "Understand starting prices, inclusions, exclusions, and possible additional costs.", href: "/compare" },
    { icon: BedDouble, title: "Hotels & stays", copy: "Compare rooms, accessibility features, nightly rates, and booking policies.", href: "/support" },
    { icon: UsersRound, title: "Interpreters & companions", copy: "Choose language and non-medical travel support for your itinerary.", href: "/support" },
    { icon: TrainFront, title: "Arriving in Jakarta", copy: "Use public transport and drop-off information on each facility page.", href: "/explore" },
    { icon: ShieldCheck, title: "Privacy & safety", copy: "Use inquiries for non-clinical coordination, never for diagnosis or emergencies.", href: "/feedback" },
  ] : guideTopics;
  const checklist = isEnglish ? beforeInquiryEn : beforeInquiry;
  const t = isEnglish ? { eyebrow: "HEALTH JOURNEY GUIDE", hero: "Be ready for your next step.", heroCopy: "A practical guide to finding services, understanding packages, sending an inquiry, and planning a health journey in Jakarta.", start: "Start here", compare: "Compare services", flow: "RECOMMENDED FLOW", flowTitle: "From discovery to coordination.", flowCopy: "Pause at any stage and continue from your dashboard after signing in.", topics: "KEY TOPICS", topicsTitle: "Information to help you compare with confidence.", topicsCopy: "General guidance only—not medical advice or a substitute for a doctor’s consultation.", checklist: "BEFORE SENDING AN INQUIRY", checklistTitle: "Prepare only what is needed.", checklistCopy: "Inquiries are for initial coordination. Partners may request more details through the appropriate channel.", find: "Find a service", transparency: "PATIENT TRANSPARENCY", rights: "Questions worth asking.", rightsCopy: "Before accepting a service or booking, ask for written information about package inclusions, exclusions, estimated total, schedule, cancellation, and follow-up.", compareData: "View comparison data", faq: "FAQ", faqTitle: "Common questions before you start.", next: "NEXT STEP", nextTitle: "Ready to explore?", explore: "Explore services", travel: "Need travel support?" } : { eyebrow: "PANDUAN PERJALANAN KESEHATAN", hero: "Lebih siap mengambil langkah berikutnya.", heroCopy: "Panduan singkat untuk memilih layanan, memahami paket, mengirim inquiry, dan menata kebutuhan perjalanan kesehatan di Jakarta.", start: "Mulai dari sini", compare: "Bandingkan layanan", flow: "ALUR YANG DISARANKAN", flowTitle: "Dari pencarian sampai koordinasi.", flowCopy: "Anda dapat berhenti di tahap mana pun dan kembali melanjutkan dari dashboard setelah masuk.", topics: "TOPIK PENTING", topicsTitle: "Informasi yang membantu Anda membandingkan dengan tenang.", topicsCopy: "Semua konten ini adalah panduan umum, bukan rekomendasi medis atau pengganti konsultasi dokter.", checklist: "SEBELUM MENGIRIM INQUIRY", checklistTitle: "Siapkan informasi secukupnya.", checklistCopy: "Inquiry dirancang untuk koordinasi awal. Mitra akan meminta detail tambahan melalui kanal yang sesuai bila diperlukan.", find: "Cari layanan", transparency: "TRANSPARANSI PASIEN", rights: "Hal yang layak Anda tanyakan.", rightsCopy: "Sebelum menyetujui layanan atau booking, minta informasi tertulis tentang cakupan paket, pengecualian, estimasi total, jadwal, pembatalan, dan rencana tindak lanjut.", compareData: "Lihat data perbandingan", faq: "FAQ", faqTitle: "Pertanyaan dasar sebelum mulai.", next: "LANGKAH BERIKUTNYA", nextTitle: "Sudah siap mulai menjelajah?", explore: "Jelajahi layanan", travel: "Butuh dukungan perjalanan?" };
  return <main className="guide-page">
    <section className="guide-hero"><div className="container guide-hero-grid"><div><p className="guide-eyebrow"><MapPinned size={15} /> {t.eyebrow}</p><h1>{t.hero}</h1><p className="guide-hero-copy">{t.heroCopy}</p><div className="guide-hero-actions"><Link href="#mulai" className="btn btn-coral">{t.start} <ArrowRight size={16} /></Link><Link href="/compare" className="btn guide-light-button">{t.compare}</Link></div></div><div className="guide-hero-panel"><span>JAKARTA HEALTH JOURNEY</span><strong>{isEnglish ? <>Browse.<br />Choose.<br />Coordinate.</> : <>Jelajahi.<br />Pilih.<br />Koordinasikan.</>}</strong><small>{isEnglish ? "Public information for your initial planning." : "Informasi publik untuk membantu persiapan awal."}</small></div></div></section>

    <section id="mulai" className="guide-section"><div className="container"><div className="guide-section-heading"><div><p>{t.flow}</p><h2>{t.flowTitle}</h2></div><span>{t.flowCopy}</span></div><div className="guide-step-grid">{steps.map((step) => { const Icon = step.icon; return <article key={step.number}><div className="guide-step-top"><span>{step.number}</span><Icon size={21} /></div><h3>{step.title}</h3><p>{step.copy}</p><Link href={step.href}>{step.cta} <ArrowRight size={14} /></Link></article>; })}</div></div></section>

    <section className="guide-section guide-soft"><div className="container"><div className="guide-section-heading"><div><p>{t.topics}</p><h2>{t.topicsTitle}</h2></div><span>{t.topicsCopy}</span></div><div className="guide-topic-grid">{topics.map((topic) => { const Icon = topic.icon; return <Link href={topic.href} className="guide-topic-card" key={topic.title}><Icon size={22} /><h3>{topic.title}</h3><p>{topic.copy}</p><ArrowRight size={17} /></Link>; })}</div></div></section>

    <section className="guide-section"><div className="container guide-checklist-layout"><div><p className="guide-eyebrow guide-eyebrow-dark">{t.checklist}</p><h2>{t.checklistTitle}</h2><p>{t.checklistCopy}</p><Link href="/explore" className="btn btn-primary">{t.find} <ArrowRight size={16} /></Link></div><div className="guide-checklist">{checklist.map((item, index) => <div key={item}><span>{String(index + 1).padStart(2, "0")}</span><ShieldCheck size={17} /><b>{item}</b></div>)}</div></div></section>

    <section className="guide-section guide-rights"><div className="container guide-rights-grid"><div><p>{t.transparency}</p><h2>{t.rights}</h2></div><div><p>{t.rightsCopy}</p><Link href="/compare">{t.compareData} <ArrowRight size={15} /></Link></div></div></section>

    <section className="guide-section guide-faq"><div className="container"><div className="guide-section-heading"><div><p>{t.faq}</p><h2>{t.faqTitle}</h2></div></div><div className="guide-faq-grid">{isEnglish ? <><details open><summary><HelpCircle size={18} />Does JHJ provide diagnoses?</summary><p>No. JHJ is a public information and non-clinical inquiry coordination platform. Contact a facility directly for medical questions.</p></details><details><summary><HelpCircle size={18} />Are package prices final?</summary><p>No. MVP prices are illustrative. Confirm final price, inclusions, and availability through an inquiry.</p></details><details><summary><HelpCircle size={18} />Why do I need an account?</summary><p>An account keeps inquiries, schedules, cancellations, and partner updates in your patient dashboard.</p></details></> : <><details open><summary><HelpCircle size={18} />Apakah JHJ memberikan diagnosis?</summary><p>Tidak. JHJ adalah platform informasi publik dan koordinasi inquiry non-klinis. Untuk pertanyaan medis, hubungi fasyankes secara langsung.</p></details><details><summary><HelpCircle size={18} />Apakah harga paket sudah final?</summary><p>Belum. Harga pada MVP adalah ilustrasi. Konfirmasi harga akhir, cakupan, dan ketersediaan langsung melalui inquiry.</p></details><details><summary><HelpCircle size={18} />Mengapa saya perlu membuat akun?</summary><p>Akun membantu menyimpan inquiry, jadwal, pembatalan, dan pembaruan dari mitra dalam dashboard pasien.</p></details></>}</div></div></section>

    <section className="guide-cta"><div className="container"><div><p>{t.next}</p><h2>{t.nextTitle}</h2></div><div><Link href="/explore" className="btn btn-coral">{t.explore} <ArrowRight size={16} /></Link><Link href="/support" className="guide-cta-link">{t.travel} <ArrowRight size={15} /></Link></div></div></section>
  </main>;
}
