import Link from "next/link";
import { ArrowRight, Building2, ClipboardCheck, HeartHandshake, Hotel, ShieldCheck, Stethoscope, UserRound } from "lucide-react";

type AccountKey = "patient" | "jhj-admin" | "facility-admin" | "support-admin" | "reviewer";

export const accountLanding = {
  patient: { eyebrow: "UNTUK PASIEN & KELUARGA", title: "Your care journey, with Jakarta by your side.", description: "Temukan layanan terverifikasi, susun rencana perjalanan, dan kirim inquiry non-klinis dengan lebih percaya diri.", icon: HeartHandshake, accent: "coral", action: "Jelajahi layanan", href: "/explore", tasks: ["Cari fasilitas sesuai kebutuhan", "Bandingkan layanan dan lokasi", "Rencanakan dukungan perjalanan"] },
  "jhj-admin": { eyebrow: "ADMIN JAKARTA HEALTH JOURNEY", title: "Protect trust at every point of care.", description: "Kelola standar platform, mitra, pengaduan, dan audit untuk menjaga pengalaman medical tourism Jakarta tetap tepercaya.", icon: ShieldCheck, accent: "navy", action: "Buka dashboard panitia", href: "/committee/dashboard", tasks: ["Tinjau mitra dan aplikasi baru", "Pantau feedback serta isu layanan", "Jaga jejak audit dan standar publik"] },
  "facility-admin": { eyebrow: "ADMIN FASYANKES", title: "Keep your care experience ready to welcome.", description: "Perbarui profil fasilitas, kelola inquiry, dan siapkan informasi layanan agar mudah ditemukan calon pasien.", icon: Stethoscope, accent: "teal", action: "Buka dashboard fasyankes", href: "/facility-admin/dashboard", tasks: ["Kelola profil dan layanan fasilitas", "Tindak lanjuti inquiry non-klinis", "Lengkapi proses verifikasi"] },
  "support-admin": { eyebrow: "ADMIN PARTNER SUPPORT", title: "Make every stay feel considered.", description: "Untuk hotel, penerjemah, caregiver, transportasi, dan partner perjalanan yang mendukung pengalaman pasien di Jakarta.", icon: Hotel, accent: "orange", action: "Ajukan akses partner", href: "/support", tasks: ["Tampilkan layanan pendukung perjalanan", "Perbarui ketersediaan dan kontak", "Terima inquiry sesuai cakupan layanan"] },
  reviewer: { eyebrow: "REVIEWER & VERIFIKATOR", title: "Review with clarity. Decide with confidence.", description: "Tinjau kelayakan partner dan tangani feedback berdasarkan standar layanan Jakarta Health Journey.", icon: ClipboardCheck, accent: "blue", action: "Buka area verifikasi", href: "/committee/verification", tasks: ["Verifikasi informasi partner", "Tinjau feedback yang masuk", "Buat keputusan berbasis standar"] },
} as const;

const icons = { patient: UserRound, "jhj-admin": ShieldCheck, "facility-admin": Building2, "support-admin": Hotel, reviewer: ClipboardCheck } as const;

export function AccountDirectory() {
  return <main className="account-directory"><section className="account-directory-hero"><div className="container"><p className="eyebrow-light">JAKARTA HEALTH JOURNEY PORTAL</p><h1>Satu perjalanan.<br /><em>Lima peran penting.</em></h1><p>Pilih ruang kerja sesuai peran Anda untuk memulai perjalanan yang aman, responsif, dan terkoordinasi.</p></div></section><section className="container account-grid">{(Object.keys(accountLanding) as AccountKey[]).map(key => { const item = accountLanding[key]; const Icon = icons[key]; return <Link key={key} href={`/accounts/${key}`} className={`account-directory-card accent-${item.accent}`}><span className="account-icon"><Icon size={24} /></span><p>{item.eyebrow}</p><h2>{key === "jhj-admin" ? "Jakarta Health Journey" : key === "facility-admin" ? "Fasyankes" : key === "support-admin" ? "Partner Support" : key === "patient" ? "Pasien & Keluarga" : "Reviewer"}</h2><span className="account-arrow"><ArrowRight size={19} /></span></Link>})}</section></main>;
}

export function AccountLanding({ account }: { account: AccountKey }) {
  const item = accountLanding[account]; const Icon = item.icon;
  return <main className={`account-page accent-${item.accent}`}><section className="account-page-hero"><div className="container account-page-layout"><div><Link href="/accounts" className="account-back">← Semua jenis akun</Link><p className="eyebrow-light">{item.eyebrow}</p><h1>{item.title}</h1><p>{item.description}</p><Link className="btn btn-coral" href={item.href}>{item.action}<ArrowRight size={18} /></Link></div><div className="account-symbol"><Icon size={92} strokeWidth={1.15} /></div></div></section><section className="container account-tasks"><div><p className="eyebrow">DESIGNED FOR YOUR ROLE</p><h2>Yang dapat Anda lakukan.</h2></div><div className="account-task-list">{item.tasks.map((task, index) => <div key={task}><span>0{index + 1}</span><p>{task}</p></div>)}</div></section><section className="container account-safety"><ShieldCheck size={25} /><div><b>Akses berbasis peran</b><p>Setelah autentikasi Appwrite diaktifkan, halaman ini akan mengarahkan pengguna ke dashboard sesuai izin akun mereka.</p></div></section></main>;
}
