"use client";

import Image from "next/image";
import Link from "next/link";
import { ArrowRight, CheckCircle2, Compass, MapPin, ShieldCheck, Sparkles } from "lucide-react";
import { PublicShell } from "@/components/layouts/public-shell";
import { useLanguage } from "@/features/i18n/language-context";

const publicBasePath = process.env.NEXT_PUBLIC_BASE_PATH ?? "";
const journeySteps = [["01", "Jelajahi", "Temukan fasilitas dan layanan terverifikasi."], ["02", "Rencanakan", "Pilih layanan serta dukungan perjalanan."], ["03", "Terhubung", "Kirim inquiry non-klinis dengan aman."], ["04", "Tiba", "Lanjutkan perjalanan dengan lebih tenang."]];
const valueCards = [[ShieldCheck, "Pilihan tepercaya", "Mitra ditinjau sebelum tampil dalam katalog publik."], [Compass, "Anda tetap memegang kendali", "Bandingkan pilihan dan hubungi layanan sesuai kebutuhan Anda."], [CheckCircle2, "Dukungan terarah", "Rencanakan perawatan dan perjalanan tanpa kehilangan kendali."]] as const;

export default function Home() {
  const { isEnglish } = useLanguage();
  const copy = isEnglish ? {
    eyebrow: "JAKARTA, CARE BEYOND BORDERS", title: <>The right support<br /><em>at every step.</em></>, intro: "Find trusted healthcare services and travel support to make your visit to Jakarta clearer, more comfortable, and more in your control.", explore: "Start exploring", support: "View travel support", verified: "Verified partners", public: "Public, non-clinical information", journeyEyebrow: "SEAMLESS BY DESIGN", journeyTitle: <>One city.<br />A more confident journey.</>, journeyCopy: "Each step connects your healthcare needs with Jakarta’s warmth and energy.", confidenceEyebrow: "A PUBLIC SERVICE, DESIGNED WITH CARE", confidenceTitle: <>Made for the<br /><em>whole journey.</em></>, confidenceCopy: "A good healthcare journey starts with clear information, responsible choices, and a genuine sense of welcome.", partner: "Explore partners", welcome: "WELCOME TO JAKARTA", welcomeTitle: <>Care can feel<br />like a warm welcome.</>, cityNote: "Your care gateway", verifiedNote: "Built for your confidence", alt: "Illustration of a Jakarta health journey with Monas, transport, hotels, and healthcare facilities."
  } : {
    eyebrow: "JAKARTA, PERAWATAN MELAMPAUI BATAS", title: <>Dukungan yang tepat<br /><em>di setiap langkah.</em></>, intro: "Temukan layanan kesehatan tepercaya dan dukungan perjalanan yang membuat kunjungan Anda ke Jakarta terasa lebih jelas, nyaman, dan terkendali.", explore: "Mulai jelajahi", support: "Lihat dukungan perjalanan", verified: "Mitra terverifikasi", public: "Informasi publik, non-klinis", journeyEyebrow: "ALUR YANG TERARAH", journeyTitle: <>Satu kota.<br />Perjalanan kesehatan yang lebih terarah.</>, journeyCopy: "Dari menemukan layanan hingga tiba di Jakarta, setiap langkah membantu Anda menyiapkan perjalanan dengan lebih jelas.", confidenceEyebrow: "LAYANAN PUBLIK, DIRANCANG DENGAN KEPEDULIAN", confidenceTitle: <>Untuk seluruh<br /><em>perjalanan Anda.</em></>, confidenceCopy: "Perjalanan kesehatan yang baik dimulai dari informasi yang jelas, pilihan yang bertanggung jawab, dan sambutan yang tulus.", partner: "Jelajahi mitra", welcome: "SELAMAT DATANG DI JAKARTA", welcomeTitle: <>Jakarta menyambut<br /><em>perjalanan Anda dengan hangat.</em></>, cityNote: "Gerbang perawatan Anda", verifiedNote: "Dibuat agar Anda lebih yakin", alt: "Ilustrasi perjalanan kesehatan di Jakarta dengan Monas, transportasi, hotel, dan fasilitas kesehatan."
  };
  const journey = isEnglish ? [["01", "Explore", "Find verified facilities and services."], ["02", "Plan", "Choose services and travel support."], ["03", "Connect", "Send a secure non-clinical inquiry."], ["04", "Arrive", "Continue your journey with confidence."]] : journeySteps;
  const values = isEnglish ? [[ShieldCheck, "Trusted choices", "Partners are reviewed before appearing in the public directory."], [Compass, "You stay in control", "Compare options and contact services based on your own needs."], [CheckCircle2, "Guided support", "Plan care and travel without losing control of the journey."]] : valueCards;

  return <PublicShell><main>
    <section className="hero-premium"><div className="hero-orb hero-orb-one" /><div className="hero-orb hero-orb-two" />
      <div className="container hero-layout"><div className="hero-copy reveal-up"><span className="eyebrow-light"><Sparkles size={14} /> {copy.eyebrow}</span><h1>{copy.title}</h1><p>{copy.intro}</p><div className="hero-actions"><Link className="btn btn-coral" href="/explore">{copy.explore} <ArrowRight size={18} /></Link><Link className="text-link-light" href="/support">{copy.support} <ArrowRight size={16} /></Link></div><div className="hero-trust"><span><ShieldCheck size={17} /> {copy.verified}</span><i /><span>{copy.public}</span></div></div>
        <div className="hero-art reveal-up-delay"><div className="flight-path"><span>✦</span></div><div className="hero-image-frame"><Image src={`${publicBasePath}/images/jakarta-health-journey-hero.png`} alt={copy.alt} fill priority sizes="(max-width: 760px) 100vw, 52vw" style={{ objectFit: "contain" }} /></div><div className="floating-note note-top"><MapPin size={16} /><span><b>Jakarta</b><small>{copy.cityNote}</small></span></div><div className="floating-note note-bottom"><span className="note-check">✓</span><span><b>{copy.verified}</b><small>{copy.verifiedNote}</small></span></div></div>
      </div>
    </section>
    <section className="container journey-section"><div className="section-heading"><div><p className="eyebrow">{copy.journeyEyebrow}</p><h2>{copy.journeyTitle}</h2></div><p>{copy.journeyCopy}</p></div><div className="journey-track">{journey.map(([number, title, description]) => <article className="journey-step" key={title}><div className="step-number">{number}</div><div className="step-dot" /><h3>{title}</h3><p>{description}</p></article>)}</div></section>
    <section className="confidence-section"><div className="container confidence-layout"><div><p className="eyebrow">{copy.confidenceEyebrow}</p><h2>{copy.confidenceTitle}</h2><p className="confidence-intro">{copy.confidenceCopy}</p><Link className="btn btn-dark" href="/explore">{copy.partner} <ArrowRight size={18} /></Link></div><div className="value-grid">{values.map((value, index) => { const Icon = value[0] as typeof ShieldCheck; const title = value[1] as string; const text = value[2] as string; return <article className="value-card" key={title}><span className="value-index">0{index + 1}</span><Icon size={25} /><h3>{title}</h3><p>{text}</p></article>; })}</div></div></section>
    <section className="container invitation-section"><div className="invitation-card"><div><p className="eyebrow">{copy.welcome}</p><h2>{copy.welcomeTitle}</h2></div><Link href="/support" className="round-arrow" aria-label={copy.support}><ArrowRight size={30} /></Link></div></section>
  </main></PublicShell>;
}
