"use client";

import { PublicShell } from "@/components/layouts/public-shell";
import { useLanguage } from "@/features/i18n/language-context";

export default function TermsPage() {
  const { isEnglish } = useLanguage();
  return <PublicShell><main className="container legal-page"><p className="eyebrow">{isEnglish ? "TERMS" : "KETENTUAN"}</p><h1 className="section-title">{isEnglish ? "Use the platform for coordination." : "Gunakan platform untuk koordinasi."}</h1><p className="legal-lead">{isEnglish ? "Jakarta Health Journey provides public, non-clinical information. It does not diagnose, prescribe, guarantee availability, or replace professional medical advice." : "Jakarta Health Journey menyediakan informasi publik non-klinis. Platform ini tidak mendiagnosis, meresepkan, menjamin ketersediaan, atau menggantikan nasihat tenaga kesehatan."}</p><div className="legal-grid"><section><h2>{isEnglish ? "Partner information" : "Informasi mitra"}</h2><p>{isEnglish ? "Descriptions, prices, credentials, reviews, and availability must be confirmed with the partner before a decision or booking." : "Deskripsi, harga, kredensial, ulasan, dan ketersediaan harus dikonfirmasi kepada mitra sebelum mengambil keputusan atau melakukan booking."}</p></section><section><h2>{isEnglish ? "Safe use" : "Penggunaan yang aman"}</h2><p>{isEnglish ? "Use inquiries for initial coordination only. For symptoms, diagnosis, treatment, or emergencies, contact a qualified healthcare provider or emergency service directly." : "Gunakan inquiry hanya untuk koordinasi awal. Untuk gejala, diagnosis, pengobatan, atau keadaan darurat, hubungi tenaga kesehatan atau layanan darurat secara langsung."}</p></section><section><h2>{isEnglish ? "Prototype status" : "Status prototipe"}</h2><p>{isEnglish ? "Some profiles and prices are illustrative demo content. Publication, moderation, and partner verification workflows must be completed before operational use." : "Sebagian profil dan harga adalah konten ilustrasi demo. Alur publikasi, moderasi, dan verifikasi mitra harus diselesaikan sebelum digunakan secara operasional."}</p></section></div></main></PublicShell>;
}
