"use client";

import { PublicShell } from "@/components/layouts/public-shell";
import { useLanguage } from "@/features/i18n/language-context";

export default function PrivacyPage() {
  const { isEnglish } = useLanguage();
  return <PublicShell><main className="container legal-page"><p className="eyebrow">{isEnglish ? "PRIVACY" : "PRIVASI"}</p><h1 className="section-title">{isEnglish ? "Your information, handled with care." : "Informasi Anda, dikelola dengan hati-hati."}</h1><p className="legal-lead">{isEnglish ? "This prototype collects only the contact and coordination information needed to follow up a non-clinical inquiry. Do not submit medical records, diagnoses, laboratory results, identity documents, or emergency information." : "Prototipe ini hanya mengumpulkan informasi kontak dan koordinasi yang diperlukan untuk menindaklanjuti inquiry non-klinis. Jangan kirim rekam medis, diagnosis, hasil laboratorium, dokumen identitas, atau informasi gawat darurat."}</p><div className="legal-grid"><section><h2>{isEnglish ? "What we use" : "Yang kami gunakan"}</h2><p>{isEnglish ? "Name, contact details, preferred service, short non-clinical purpose, travel support needs, and preferred date may be used to coordinate with a partner." : "Nama, kontak, layanan yang diminati, tujuan singkat non-klinis, kebutuhan dukungan perjalanan, dan preferensi tanggal dapat digunakan untuk koordinasi dengan mitra."}</p></section><section><h2>{isEnglish ? "Your choices" : "Pilihan Anda"}</h2><p>{isEnglish ? "You may ask for a correction or withdrawal of a pending inquiry. Partners should receive only the information necessary for the requested follow-up." : "Anda dapat meminta koreksi atau penarikan inquiry yang masih berjalan. Mitra seharusnya hanya menerima informasi yang diperlukan untuk tindak lanjut."}</p></section><section><h2>{isEnglish ? "Prototype notice" : "Catatan prototipe"}</h2><p>{isEnglish ? "This MVP is not yet a production medical record system. Storage, retention, access logging, and deletion workflows must be configured before real patient data is accepted." : "MVP ini belum merupakan sistem rekam medis produksi. Penyimpanan, retensi, pencatatan akses, dan alur penghapusan harus dikonfigurasi sebelum data pasien nyata diterima."}</p></section></div></main></PublicShell>;
}
