"use client";

import Link from "next/link";
import { ArrowRight, BadgeCheck, Languages, MapPin, Video } from "lucide-react";
import { CurrencyPrice } from "@/features/currency/currency-context";
import { useLanguage } from "@/features/i18n/language-context";

const interpreters = [
  { name: "Nadia Putri", languages: "Indonesia · English · Mandarin", focus: "Koordinasi pasien internasional", focusEn: "International patient coordination", mode: "On-site & pendampingan", modeEn: "On-site & companion support", rate: "Rp850.000–Rp1.250.000 / hari", image: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=640&q=80", bio: "Mendampingi komunikasi operasional pasien dan keluarga untuk agenda konsultasi, registrasi, serta perjalanan di Jakarta.", bioEn: "Supports patients and families with operational communication for consultations, registration, and travel in Jakarta." },
  { name: "Rafi Pratama", languages: "Indonesia · English · Arabic", focus: "Hospitality & mobilitas", focusEn: "Hospitality & mobility", mode: "On-site", modeEn: "On-site", rate: "Rp900.000–Rp1.400.000 / hari", image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=640&q=80", bio: "Berpengalaman mendukung tamu dari kedatangan, koordinasi hotel, hingga komunikasi non-klinis dengan partner layanan.", bioEn: "Experienced in supporting guests from arrival and hotel coordination through non-clinical partner communication." },
  { name: "Mei Lin Tan", languages: "Indonesia · English · Mandarin", focus: "Konsultasi jarak jauh", focusEn: "Remote consultation support", mode: "Video & on-site", modeEn: "Video & on-site", rate: "Rp750.000–Rp1.150.000 / hari", image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=640&q=80", bio: "Membantu keluarga memahami informasi operasional dan menjembatani komunikasi lintas bahasa sebelum maupun saat kunjungan.", bioEn: "Helps families understand operational information and bridge communication before and during a visit." },
  { name: "Alya Rahman", languages: "Indonesia · English · Japanese", focus: "Pendampingan keluarga", focusEn: "Family companion support", mode: "On-site & perjalanan", modeEn: "On-site & travel", rate: "Rp850.000–Rp1.300.000 / hari", image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=640&q=80", bio: "Fokus pada kebutuhan komunikasi keluarga, pengaturan agenda, serta dukungan bahasa untuk perjalanan dan akomodasi di Jakarta.", bioEn: "Focuses on family communication, itinerary coordination, and language support for travel and accommodation in Jakarta." },
  { name: "Daniel Wijaya", languages: "Indonesia · English · Korean", focus: "Koordinasi kunjungan", focusEn: "Visit coordination", mode: "On-site & video", modeEn: "On-site & video", rate: "Rp800.000–Rp1.250.000 / hari", image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=640&q=80", bio: "Mendukung komunikasi operasional sebelum kunjungan, pendampingan agenda, dan koordinasi layanan perjalanan pasien.", bioEn: "Supports pre-visit communication, scheduled activities, and patient travel-service coordination." },
] as const;

const categories = [["Penerjemah on-site", "Hadir langsung untuk agenda yang disepakati.", "On-site interpreters", "Available in person for agreed activities."], ["Pendamping perjalanan", "Dukungan bahasa untuk hotel, transportasi, dan koordinasi non-klinis.", "Travel companions", "Language support for hotels, transport, and non-clinical coordination."], ["Video interpreting", "Komunikasi jarak jauh untuk persiapan perjalanan dan konsultasi administratif.", "Video interpreting", "Remote communication for travel preparation and administrative consultations."], ["Bahasa isyarat", "Permintaan akan disesuaikan dengan ketersediaan mitra terverifikasi.", "Sign language", "Requests are matched with verified partner availability."]] as const;

export function LanguageSupport() {
  const { isEnglish } = useLanguage();
  const copy = isEnglish ? { eyebrow: "LANGUAGE SUPPORT", title: <>Understood at<br /><em>every step.</em></>, intro: "Find interpreters for service communication and travel. All support is non-clinical and does not replace a healthcare professional’s decision.", sample: "Sample profile", credential: "Holds Basic Life Support and basic nursing training certificates to support patient readiness outside the hospital.", action: "Request an interpreter", noteTitle: "Illustrative daily rate.", note: "Rates exclude transport, additional time, or special requirements. Final rates and availability are confirmed by the partner before service begins.", credentialNote: "BLS and basic nursing credentials shown on these cards are sample data; certificates must be verified by Jakarta Health Journey before a profile is published as a verified partner.", credit: "Sample photos from" } : { eyebrow: "DUKUNGAN BAHASA", title: <>Dipahami dalam<br /><em>setiap langkah.</em></>, intro: "Temukan penerjemah untuk komunikasi layanan dan perjalanan. Semua dukungan bersifat non-klinis dan tidak menggantikan keputusan tenaga kesehatan.", sample: "Contoh profil", credential: "Memiliki sertifikat Basic Life Support dan pelatihan keperawatan dasar untuk menunjang kesiagaan pendampingan pasien di luar rumah sakit.", action: "Ajukan inquiry penerjemah", noteTitle: "Tarif contoh per hari.", note: "Kisaran belum mencakup transportasi, waktu tambahan, atau kebutuhan khusus. Tarif dan ketersediaan final dikonfirmasi oleh mitra sebelum layanan berjalan.", credentialNote: "Kredensial BLS dan pelatihan keperawatan dasar pada kartu di atas adalah data contoh; dokumen sertifikat wajib diverifikasi oleh Jakarta Health Journey sebelum profil dipublikasikan sebagai mitra terverifikasi.", credit: "Foto contoh dari" };
  return <section className="language-support" id="dukungan-bahasa"><div className="language-heading"><div><p className="eyebrow"><Languages size={14} /> {copy.eyebrow}</p><h2>{copy.title}</h2></div><p>{copy.intro}</p></div><div className="language-categories">{categories.map(([title, text, titleEn, textEn]) => <div key={title}><BadgeCheck size={18} /><b>{isEnglish ? titleEn : title}</b><span>{isEnglish ? textEn : text}</span></div>)}</div><div className="interpreter-grid">{interpreters.map((interpreter) => <article className="interpreter-card" key={interpreter.name}><div className="interpreter-photo" role="img" aria-label={`${isEnglish ? "Sample photo" : "Foto contoh"} ${interpreter.name}`} style={{ backgroundImage: `url(${interpreter.image})` }} /><div className="interpreter-body"><div className="interpreter-top"><span className="badge badge-verified"><BadgeCheck size={13} />{copy.sample}</span><span className="interpreter-rate"><CurrencyPrice value={interpreter.rate} /></span></div><h3>{interpreter.name}</h3><p className="interpreter-languages"><Languages size={15} />{interpreter.languages}</p><p className="interpreter-focus"><MapPin size={15} />{isEnglish ? interpreter.focusEn : interpreter.focus} · {isEnglish ? interpreter.modeEn : interpreter.mode}</p><p className="interpreter-bio">{isEnglish ? interpreter.bioEn : interpreter.bio}</p><p className="interpreter-credential"><BadgeCheck size={15} />{copy.credential}</p><Link className="interpreter-action" href="/register?next=%2Fsupport">{copy.action} <ArrowRight size={16} /></Link></div></article>)}</div><div className="language-note"><Video size={20} /><p><b>{copy.noteTitle}</b> {copy.note}</p></div><p className="language-credential-note"><BadgeCheck size={15} />{copy.credentialNote}</p><p className="language-credit">{copy.credit} <a href="https://unsplash.com" target="_blank" rel="noreferrer">Unsplash</a>.</p></section>;
}
