import Link from "next/link";
import { ArrowRight, BadgeCheck, Languages, MapPin, Video } from "lucide-react";

const interpreters = [
  { name: "Nadia Putri", languages: "Indonesia · English · Mandarin", focus: "Koordinasi pasien internasional", mode: "On-site & pendampingan", rate: "Rp850.000–Rp1.250.000 / hari", image: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=640&q=80", bio: "Mendampingi komunikasi operasional pasien dan keluarga untuk agenda konsultasi, registrasi, serta perjalanan di Jakarta." },
  { name: "Rafi Pratama", languages: "Indonesia · English · Arabic", focus: "Hospitality & mobilitas", mode: "On-site", rate: "Rp900.000–Rp1.400.000 / hari", image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=640&q=80", bio: "Berpengalaman mendukung tamu dari kedatangan, koordinasi hotel, hingga komunikasi non-klinis dengan partner layanan." },
  { name: "Mei Lin Tan", languages: "Indonesia · English · Mandarin", focus: "Konsultasi jarak jauh", mode: "Video & on-site", rate: "Rp750.000–Rp1.150.000 / hari", image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=640&q=80", bio: "Membantu keluarga memahami informasi operasional dan menjembatani komunikasi lintas bahasa sebelum maupun saat kunjungan." },
  { name: "Alya Rahman", languages: "Indonesia · English · Japanese", focus: "Pendampingan keluarga", mode: "On-site & perjalanan", rate: "Rp850.000–Rp1.300.000 / hari", image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=640&q=80", bio: "Fokus pada kebutuhan komunikasi keluarga, pengaturan agenda, serta dukungan bahasa untuk perjalanan dan akomodasi di Jakarta." },
  { name: "Daniel Wijaya", languages: "Indonesia · English · Korean", focus: "Koordinasi kunjungan", mode: "On-site & video", rate: "Rp800.000–Rp1.250.000 / hari", image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=640&q=80", bio: "Mendukung komunikasi operasional sebelum kunjungan, pendampingan agenda, dan koordinasi layanan perjalanan pasien." },
] as const;

const categories = [["Penerjemah on-site", "Hadir langsung untuk agenda yang disepakati."], ["Pendamping perjalanan", "Dukungan bahasa untuk hotel, transportasi, dan koordinasi non-klinis."], ["Video interpreting", "Komunikasi jarak jauh untuk persiapan perjalanan dan konsultasi administratif."], ["Bahasa isyarat", "Permintaan akan disesuaikan dengan ketersediaan mitra terverifikasi."]] as const;

export function LanguageSupport() {
  return <section className="language-support" id="dukungan-bahasa"><div className="language-heading"><div><p className="eyebrow"><Languages size={14} /> DUKUNGAN BAHASA</p><h2>Dipahami dalam<br /><em>setiap langkah.</em></h2></div><p>Temukan penerjemah untuk komunikasi layanan dan perjalanan. Semua dukungan bersifat non-klinis dan tidak menggantikan keputusan tenaga kesehatan.</p></div><div className="language-categories">{categories.map(([title, text]) => <div key={title}><BadgeCheck size={18} /><b>{title}</b><span>{text}</span></div>)}</div><div className="interpreter-grid">{interpreters.map((interpreter) => <article className="interpreter-card" key={interpreter.name}><div className="interpreter-photo" role="img" aria-label={`Foto contoh ${interpreter.name}`} style={{ backgroundImage: `url(${interpreter.image})` }} /><div className="interpreter-body"><div className="interpreter-top"><span className="badge badge-verified"><BadgeCheck size={13} />Contoh profil</span><span className="interpreter-rate">{interpreter.rate}</span></div><h3>{interpreter.name}</h3><p className="interpreter-languages"><Languages size={15} />{interpreter.languages}</p><p className="interpreter-focus"><MapPin size={15} />{interpreter.focus} · {interpreter.mode}</p><p className="interpreter-bio">{interpreter.bio}</p><p className="interpreter-credential"><BadgeCheck size={15} />Memiliki sertifikat Basic Life Support dan pelatihan keperawatan dasar untuk menunjang kesiagaan pendampingan pasien di luar rumah sakit.</p><Link className="interpreter-action" href="/register?next=%2Fsupport">Ajukan inquiry penerjemah <ArrowRight size={16} /></Link></div></article>)}</div><div className="language-note"><Video size={20} /><p><b>Tarif contoh per hari.</b> Kisaran belum mencakup transportasi, waktu tambahan, atau kebutuhan khusus. Tarif dan ketersediaan final dikonfirmasi oleh mitra sebelum layanan berjalan.</p></div><p className="language-credential-note"><BadgeCheck size={15} />Kredensial BLS dan pelatihan keperawatan dasar pada kartu di atas adalah data contoh; dokumen sertifikat wajib diverifikasi oleh Jakarta Health Journey sebelum profil dipublikasikan sebagai mitra terverifikasi.</p><p className="language-credit">Foto contoh dari <a href="https://unsplash.com" target="_blank" rel="noreferrer">Unsplash</a>.</p></section>;
}
